services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - my_network
    restart: always
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - my_network
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - my_network
    restart: always
    depends_on:
      - mariadb

networks:
  my_network:
    driver: bridge

volumes:
  data:
