services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    restart: always
    depends_on:
      - wordpress

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  my_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR}mariadb_data
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR}wordpress_data
      o: bind
